trigger: none
pr:
  - master
pool:
  vmImage: 'windows-latest'
stages:
  - stage: BuildAndTest
    jobs:
    - job: BuildAndTestJob
      displayName: Build
      variables:
        - name: solution
          value: '**/*.sln'
        - name: buildPlatform
          value: 'anycpu'
        - name: buildConfiguration
          value: 'Release'
        - group: Cap Dev - CI
      steps:
        - task: NuGetToolInstaller@1
          displayName: Install NuGet
        - task: NuGetCommand@2
          displayName: Restore NuGet packages
          inputs:
            restoreSolution: '$(solution)'
        - task: VSBuild@1
          displayName: Build solution
          inputs:
            solution: '$(solution)'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        
        - task: VSTest@2
          displayName: Run tests
          env:
            CAPGEMINI_PACKAGE_DEPLOYER_TESTS_URL: $(URL)
            CAPGEMINI_PACKAGE_DEPLOYER_TESTS_USERNAME: $(User ADO Integration Username)
            CAPGEMINI_PACKAGE_DEPLOYER_TESTS_PASSWORD: $(User ADO Integration Password)
          inputs:
            codeCoverageEnabled: true
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
            testAssemblyVer2: '**\*Tests.dll' 
            searchFolder: tests
        
        - task: NuGetCommand@2
          displayName: Pack NuGet package
          inputs:
            command: pack
            packagesToPack: src/Capgemini.PowerApps.Deploment/Capgemini.PowerApps.Deployment.csproj
            includeReferencedProjects: true
            packDestination: '$(Build.ArtifactStagingDirectory)/out'
        - publish: $(Build.ArtifactStagingDirectory)/out
          displayName: Publish NuGet artifact
          artifact: Capgemini.PowerApps.Deployment
