name: $(GITVERSION_FullSemVer)
trigger: none
pr:
  - master
pool:
  vmImage: 'windows-latest'
stages:
  - stage: BuildAndTest
    displayName: Build and Test
    jobs:
    - template: templates/build-and-test-job.yml
