name: $(GITVERSION_FullSemVer)

trigger: none

pr:
  - master

pool:
  vmImage: windows-latest

stages:
  - template: templates/build-and-test-stages.yml
    parameters:
      environmentIdentifier: $[ coalesce(variables['System.PullRequest.PullRequestNumber'], variables['Build.BuildId']) ]
      environmentDisplayName: Package Deployer Template - PR
      environmentDomainName: pdt-pr