//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\max.ewing\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://capgeminibasedev.api.crm4.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"Capgemini.Xrm.Deployment.IntegrationTests.Model" /out:"C:\Capgemini.CRM2016\Capgemini.Crm\Capgemini.Xrm.Deployment.IntegrationTests\Model\Entities\CapgeminiBaseContext.cs" /servicecontextname:"CapgeminiBaseContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"ciauth@capgeminicrmuk.onmicrosoft.com" /password:"*************" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Capgemini.Xrm.Deployment.IntegrationTests.Model
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.0.749")]
	public partial class CapgeminiBaseContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CapgeminiBaseContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.ActivityParty"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.ActivityParty> ActivityPartySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.ActivityParty>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.Annotation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.Annotation> AnnotationSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.Annotation>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.Appointment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.Appointment> AppointmentSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.Appointment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.BusinessUnit"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.BusinessUnit> BusinessUnitSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.BusinessUnit>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.Calendar"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.Calendar> CalendarSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.Calendar>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.cap_autonumberdefinition"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.cap_autonumberdefinition> cap_autonumberdefinitionSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.cap_autonumberdefinition>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.cap_autonumberrequest"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.cap_autonumberrequest> cap_autonumberrequestSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.cap_autonumberrequest>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.cap_configurationparameter"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.cap_configurationparameter> cap_configurationparameterSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.cap_configurationparameter>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.cap_Log"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.cap_Log> cap_LogSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.cap_Log>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.Contact> ContactSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.CustomerAddress"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.CustomerAddress> CustomerAddressSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.CustomerAddress>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.Incident"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.Incident> IncidentSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.Incident>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.InteractionForEmail"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.InteractionForEmail> InteractionForEmailSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.InteractionForEmail>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.Letter"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.Letter> LetterSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.Letter>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.PhoneCall"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.PhoneCall> PhoneCallSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.PhoneCall>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.Queue"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.Queue> QueueSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.Queue>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.QueueItem"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.QueueItem> QueueItemSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.QueueItem>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.QueueMembership"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.QueueMembership> QueueMembershipSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.QueueMembership>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.Role"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.Role> RoleSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.Role>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.Solution"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.Solution> SolutionSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.Solution>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.SystemUser> SystemUserSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.SystemUser>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.Task"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.Task> TaskSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.Task>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.Team"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.Team> TeamSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.Team>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.TransactionCurrency"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.TransactionCurrency> TransactionCurrencySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.TransactionCurrency>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.WebResource"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.WebResource> WebResourceSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.WebResource>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Capgemini.Xrm.Deployment.IntegrationTests.Model.Workflow"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Capgemini.Xrm.Deployment.IntegrationTests.Model.Workflow> WorkflowSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Capgemini.Xrm.Deployment.IntegrationTests.Model.Workflow>();
			}
		}
	}
}